accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
	
	url(r'^signup/$',views.signup_view,name="signup"),
	url(r'^login/$',views.login_view,name="login"),
	url(r'^logout/$',views.logout_view,name="logout"),
	url(r'^profile/$',views.profile_view,name="profile")

]

articles/urls.py
from django.conf.urls import url
from . import views

#namespacing
app_name = 'articles'

urlpatterns = [
    #r means raw string
 	url(r'^$',views.article_list, name ="list"),
 	url(r'^article_search$',views.article_search, name ="search"),
 	url(r'^create/$',views.article_create,name="create"),
 	#below is a name capturing group ?P<name of thing we want to capture>   
 	url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="detail"),
 ]

djangonautic/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')),
 	url(r'^about/$',views.about),
 	url(r'^$',article_views.article_list,name="home"),   
 ]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    # add additional fields in here
    bio = models.TextField(max_length=500,blank=True)
    dob = models.DateField(blank=True)
    country = models.CharField(max_length=500,blank=True)
    
    def __str__(self):
        return self.username

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.conf import settings

# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(default=datetime.now()) 
	thumb = models.ImageField(default='default.jpg',blank=True)
	author = models.ForeignKey(settings.AUTH_USER_MODEL,default=None,on_delete=models.PROTECT)

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:100]+'...'
		#first 50 characters

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email','bio','dob','country')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email','bio','dob','country')

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Article
		fields =['title','body','slug','thumb']

accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout
from .forms import CustomUserCreationForm
from .models import CustomUser
from django.db.models import Q

# Create your views here.
def signup_view(request):
	if request.method == 'POST':
		form = CustomUserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			#log the user in
			login(request,user)
			#difference between render and redirect
			return redirect('home')
	else:
		form = CustomUserCreationForm()
	return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
	#return HttpResponse("sagar")
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#login the user
			user = form.get_user()
			login(request,user)
			if 'kittho_aaye_ho' in request.POST:
				return redirect(request.POST.get('kittho_aaye_ho'))
			else:
				return redirect('articles:list')
	else:
		form = AuthenticationForm()
	return render(request,"accounts/login.html",{'form':form})

def logout_view(request):
	#return HttpResponse("sagar")
	if request.method == 'POST':
		logout(request)
		return redirect('articles:list')

def profile_view(request):
	if request.method == 'POST':
		var = CustomUser.objects.filter(Q(username=request.user))
		return render(request,"accounts/profile.html",{'profiles':var } )

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
from django.db.models import Q


# Create your views here.
def article_list(request):
	article = Article.objects.all().order_by('date')
	return render(request,"articles/article_list.html",{'articles':article} )

def article_search(request):
	query = request.GET.get('search-box')
	article = Article.objects.filter(Q(title__icontains=query))
	return render(request,"articles/article_list.html",{'articles':article} )

def article_detail(request,slug):
	#return HttpResponse(slug)
	var = Article.objects.get(slug=slug)
	return render(request,'articles/article_detail.html',{'article':var})

@login_required(login_url="/accounts/login")
def article_create(request):
	if request.method == 'POST':
		#as files dosent come on post request so it need to be retrieved seperately to be validated
		form = forms.CreateArticle(request.POST,request.FILES)
		if form.is_valid():
			#save article to db
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('articles:list')

	else:
		form = forms.CreateArticle()
	return render(request,'articles/article_create.html',{'form':form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
	#return HttpResponse('this is homepage')
	return render(request,'homepage.html')

def about(request):
	#return HttpResponse("this is about page")
	return render(request,'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Log in</h1>
	<form class="site-form" action="{% url 'accounts:login' %}" method="post">
		<!-- a permission token specifying which client made the request.read more @https://docs.djangoproject.com/en/2.1/ref/csrf/-->
		{% csrf_token  %}
		{{ form }}
		{% if request.GET.next %}
			<input type="hidden" name="kittho_aaye_ho" value="{{request.GET.next}}">
		{% endif %}
		<input type="submit" value="Log in">
		
	</form>
		
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base_layout.html' %}

{% block content %}
	{% for item in profiles %}
		<div class="profile-detail">
			<div class="profile">
				<h2>Hey  {{ item.username }}</h2>
				<ul type=none>
					<li><b>Email:</b> {{ item.email }}</li>
					<li><b>Bio:</b> {{ item.bio }}</li>
					<li><b>Date of Birth:</b> {{ item.dob }}</li>
					<li><b>Country:</b> {{ item.country }}</li>
				</ul>
				
				

			</div>
		</div>
	{% endfor %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Signup</h1>
	<form class="site-form" action="/accounts/signup/" method="post">
		<!-- a permission token specifying which client made the request.read more @https://docs.djangoproject.com/en/2.1/ref/csrf/-->
		{% csrf_token  %}
		{{ form }}
		<input type="submit" value="SignUp">
		
	</form>
		
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
	<div class="create-article">
		<h2>Create an awesome new article
			<!-- whenever we have an upload field like thumb in this case we use enctype for encryption-->
		<form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form}}
			<input type="submit" value="Create">
		</form>	
	</div>
	<script src="/static/slugify.js"></script>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

	<div class="article-detail">
		<div class="article">
			<img src="{{ article.thumb.url }}"/>
			<h2>{{ article.title }}</h2>
			<p>{{ article.body }}</p>
			<p>{{ article.date }}</p>

		</div>
	</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}

{% block content %}
<form class="search" action="{% url 'articles:search' %}" method="GET" type="get">
	{% csrf_token %}
	<input class="search-box" type="text" placeholder="Search..." name="search-box">
	<button class ="submit" type="submit">Submit</button>
</form>
<h1>Article list</h1>
	<div class="articles">
		<!-- the below are known as template tag used for writing python code in html
		first one is used for writing python code
		second one is used to output some data -->
		
			{% for item in articles %}
				<div class ="item">
					<h2><a href="{% url 'articles:detail' slug=item.slug %}">{{item.title}}</a></h2>
					<p>{{item.snippet}}</p>
					<p>{{item.date}}</p>
					<p class="author">added by {{ item.author }}</p>
				</div>
				
			{% endfor %}
		
	</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
<head>
	<title>about</title>
</head>
<body>
<h1>this is the about page</h1>
</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}
 
<!DOCTYPE html>
<html>
<head>
	<title>Articles</title>
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
	<body>
		<header class="wrapper">
			<h1><a href="{% url 'home'%}"><img src="{% static 'logo.png' %}"></a></h1>
			<nav>
				<ul>
					{% if user.is_authenticated %}
					<li>
						<form class="logout-link" action="{%url 'accounts:logout'%}" method='POST'>
							{%csrf_token%}
							<button type="submit">Logout</button>
						</form>

					</li>
					<li><a href="{% url 'articles:create'%}" class="highlight">New Article</a></li>
					<li>
						<form class="profile-link" action="{%url 'accounts:profile'%}" method='POST'>
							{%csrf_token%}
							<button type="submit">Profile</button>
						</form>
					</li>
					
					{% else %}
					<li>
						<a href="{% url 'accounts:login'%}">Log In</a></li>
						<li><a href="{% url 'accounts:signup'%}">Sign Up</a>
					</li>
					{% endif %}
				</ul>
			</nav>
		</header>
		<div class="wrapper">
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>
<!-- <li>
						<form class="profile-link" action="url 'accounts:profile'%}" method='POST'>
							{%csrf_token%}
							<button type="submit">Profile</button>
						</form>
					</li> -->

templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>homepage</title>
</head>
<body bgcolor="black">
<h1 style="color:white;">welcome to the homepage</h1>
</html>